
# services to build

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    networks:
      - inception-network
    volumes: 
      - db_vol:/var/lib/mysql
    env_file: .env

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: always
    volumes:
      - wp_vol:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception-network
    env_file: .env

  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: always
    volumes:
      - wp_vol:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception-network

# network settings

networks:
  inception-network:
    name : inception-network
    driver : bridge

# docker volume settings

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/jwilliam/data/mysql
  wp_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/jwilliam/data/wordpress
